### ISSUE TITLE
Patch Failed (Google Pixel 2) (4.4.302) 

### ISSUE THREAD

**Issue by CEllenvia** [bmax121/KernelPatch#119]
The following two information are what I need to fix the problem

1. Your kernel image. boot.img is too big, you can use 'magiskboot unpack boot.img' to get kernel image (which named 'kernel' after unpack)

[boot.zip](https://github.com/user-attachments/files/16712941/boot.zip)

2.  The real symbol informations corresponding to your boot.img or kernel
It can be obtained through the following two commands under **root**.
```shell
echo 1 > /proc/sys/kernel/kptr_restrict
cat /proc/kallsyms
```
[kallsyms.zip](https://github.com/user-attachments/files/16713289/kallsyms.zip)

https://pastebin.ubuntu.com/p/XTQVYzwZVM/

**Comment by bmax121** [comment]
dev is good
