### ISSUE TITLE
pixel3官方镜像提取boot.img，修补之后进入系统桌面几秒卡主重启

### ISSUE THREAD

**Issue by df13954** [bmax121/KernelPatch#125]
环境：
使用10398可以正常工作，最近更新10762版本，重新修补后，启动系统进入桌面卡主几秒重启，一直反复。
这是原内核文件和修补的文件。
https://www.123pan.com/s/pKnZVv-v2Fi

**Comment by bmax121** [comment]
fixed, try 0.11.1
