### ISSUE TITLE
Patch Failed (one plus 9pro) (Device Kerenl 5.4.242.Aospa.Vishal@aserv) 

### ISSUE THREAD

**Issue by Cagarin** [bmax121/KernelPatch#14]
The following two information are what I need to fix the problem

1. Your boot.img or kernel image

Upload to here or file download path

2.  The real symbol informations corresponding to your boot.img or kernel
It can be obtained through the following two commands under **root**.
```shell
echo 1 > /proc/sys/kernel/kptr_restrict
cat /proc/kallsyms
```

Upload to here or file download path
[untitled.txt](https://github.com/bmax121/KernelPatch/files/13821318/untitled.txt)
https://drive.google.com/drive/folders/1J0GKGqAR8rwLGC5gT7xzsv7XfsbCnWjt

**Comment by bmax121** [comment]
no permssion of google driver

**Comment by Cagarin** [comment]
Hola perdona .ya te concedí a eso a la carpeta.gracias yun saludo

**Comment by Cagarin** [comment]
> Las siguientes dos informaciones son las que necesito para solucionar el problema.
> 
> 1. Su boot.img o imagen del kernel
> 
> Subir aquí o ruta de descarga de archivos
> 
> 2. La información del símbolo real correspondiente a su boot.img o kernel 
>    se puede obtener mediante los siguientes dos comandos en **root** .
> 
> ```shell
> echo 1 > /proc/sys/kernel/kptr_restrict
> cat /proc/kallsyms
> ```
> 
> Subir aquí o ruta de descarga de archivos [untitled.txt ](https://github.com/bmax121/KernelPatch/files/13821318/untitled.txt) https://drive.google.com/drive/folders/1J0GKGqAR8rwLGC5gT7xzsv7XfsbCnWjt



> sin permiso del controlador de google

Hola ya está el enlace.un saludo
