### ISSUE TITLE
Patch Failed (Google Pixel 8 Pro) (Kernel Version : 6.1.99) (OS Version : Android 15 QPR2 Beta 1) 

### ISSUE THREAD

**Issue by bookworm-coding** [bmax121/KernelPatch#142]
I'm currently using Android 15 QPR1 Beta 3(Build : AP41.240925.00) rooted by Apatch on my Google Pixel 8 Pro (Husky) without any errors while patching. 
And, I was trying to upgrade into Android 15 QPR2 Beta 1(Build : BP11.241025.006). So, I tried to patch the new boot.img with Apatch but while patching there was an error like below. It was same at the online patching method. 

### OS Version ###
Android 15 QPR2 Beta 1(Build : BP11.241025.006)

### Apatch Version ###
10763

### Kernal Version ###
6.1.99

### KernelPatch Version ###
I tried 0.10.7 and 0.11.1-dev but both failed

### Boot Image of Android 15 QPR2 Beta 1 for Husky ###
https://drive.google.com/file/d/1Cf5WwVfL9Sk9WfqpaScAC2v1ZX_bK4id/view?usp=share_link

### Error Message ###
![Screenshot of the Error Message](https://github.com/user-attachments/assets/849aef89-c8c3-40ac-89b8-94eddfc98354)

**Comment by bmax121** [comment]
or System.map

**Comment by bookworm-coding** [comment]
[symbols.txt](https://github.com/user-attachments/files/17815737/symbols.txt)
Here are the symbol informations.

**Comment by bookworm-coding** [comment]
I'm sorry, I found out that Android 16 Developer Preview 1 has been released in 11/19 for Pixel Devices. And the build number of the Preview is BP21.241018.009
So, I think that the issue about APatch not working with QPR2 Beta 1 is related to Android 16.
I think I should change the name of this to APatch not working on Android 16

**Comment by bookworm-coding** [comment]
I thought that it was because of the changes in Android 16 as the Android 16 Developer Preview 1 was released in 11/19 and it's Build is BP21.241018.009
But as I tried patching the new Android Preview with APatch, it worked well without issues.

**Comment by bmax121** [comment]
fixed, repoen if with issue
