### ISSUE TITLE
Patch Failed (Redmi Note 11) (Device 4.19.30)  The patch didnt failed, but phone didnt booted after flashing with the patched boot img

### ISSUE THREAD

**Issue by ashoktvm** [bmax121/KernelPatch#19]
The following two information are what I need to fix the problem

1. Your boot.img or kernel image

[Upload to here or file download path](https://drive.google.com/file/d/1noY6GsU98IEpjywxPHiWxGn-zO77qRs5/view?usp=sharing)

2.  The real symbol informations corresponding to your boot.img or kernel
It can be obtained through the following two commands under **root**.
```shell
echo 1 > /proc/sys/kernel/kptr_restrict
cat /proc/kallsyms
```

Upload to here or file download path

**Comment by bmax121** [comment]
Currently, there is no immediate solution. You need to troubleshoot it yourself or provide the device to me for further investigation. Or wait for update, maybe it will be solved something
