### ISSUE TITLE
MEIZU16S Failed .I need your help.thank you 

### ISSUE THREAD

**Issue by hugh1927** [bmax121/KernelPatch#24]
I can use the app to retrieve the patched file, which I named aboot.img. But when I flash it in fastboot mode, I cannot boot up properly. And can only stay on the fastboot interface
Here are the files I prepared after seeing your reply。
Kernel: 4.14.83-perf+
[Log.txt](https://github.com/bmax121/KernelPatch/files/13833964/Log.txt)
[MY boot.zip](https://github.com/bmax121/KernelPatch/files/13833975/MY.boot.zip)
[aboot.zip](https://github.com/bmax121/KernelPatch/files/13834034/aboot.zip)

**Comment by bmax121** [comment]
it's very hard to solve it if I don't have the device

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: hugh1927 ***@***.***>
Sent: Friday, January 5, 2024 2:07:56 AM
To: bmax121/KernelPatch ***@***.***>
Cc: bmax121 ***@***.***>; Assign ***@***.***>
Subject: [bmax121/KernelPatch] MEIZU16S Falid .I need your help.thank you (Issue #24)


I can use the app to retrieve the patched file, which I named aboot.img. But when I flash it in fastboot mode, I cannot boot up properly. And can only stay on the fastboot interface
Here are the files I prepared after seeing your reply。
Kernel: 4.14.83-perf+
Log.txt<https://github.com/bmax121/KernelPatch/files/13833964/Log.txt>
MY boot.zip<https://github.com/bmax121/KernelPatch/files/13833975/MY.boot.zip>
aboot.zip<https://github.com/bmax121/KernelPatch/files/13834034/aboot.zip>

―

**Comment by bmax121** [comment]
Currently, there is no immediate solution. You need to troubleshoot it yourself or provide the device to me for further investigation
