### ISSUE TITLE
Apatch image not boot on Motorola G20 (Kernel 4.14.193)

### ISSUE THREAD

**Issue by Caua77** [bmax121/KernelPatch#28]
After flashing the patched boot image, the device cannot proceed to the boot logo screen and is frozen there. The device is a Motorola G20 unisoc T700 processor.

1. Your boot.img or kernel image

https://mega.nz/file/07dk1DxY#LB0zIlcYYeZxNL4yXWYSYiq9orWFvlSBFUNwvX1JvzI

2. After flashing the patched boot image, the device is frozen on the boot logo screen.

3. KernelPatch logs

[APatch_bugreport_2024-01-10_08_07.tar.gz](https://github.com/bmax121/KernelPatch/files/13886927/APatch_bugreport_2024-01-10_08_07.tar.gz)

**Comment by bmax121** [comment]
Currently, there is no immediate solution. You need to troubleshoot it yourself or provide the device to me for further investigation
