### ISSUE TITLE
Hook via module

### ISSUE THREAD

**Issue by zrose584** [bmax121/KernelPatch#3]
I see that KernelPatch can hook kernel symbols in `before_rest_init`:

https://github.com/bmax121/KernelPatch/blob/68f9cd26efbb94f8f4561721ab065ae917cf3f27/kernel/init/init.c#L73

Is it also possible to hook symbols after the kernel has loaded, e.g. via a module that is loaded with `--load_kpm` (once that is implemented)?
Or does all hooking/patching need to be done before the kernel started? If so why?

Thank you for this project, it looks very promising and useful!

**Comment by bmax121** [comment]
Of course, I'm planning to do it, but I need some time. There will be documentation after implementation.

**Comment by bmax121** [comment]
@zrose584 KernelPatch Module has been implemented, now you can use --load_kpm.

**Comment by zrose584** [comment]
I tested it and it worked. This is useful to me, thank you!
