### ISSUE TITLE
Patch Failed (Redmi note 12 5G )(qgki-5.4.233)

### ISSUE THREAD

**Issue by Alpha-Qian** [bmax121/KernelPatch#33]
the same issue : https://github.com/bmax121/KernelPatch/issues/12

boot.img.7z: https://pixeldrain.com/u/7iXJhxpd

![Screenshot_2024-01-12-07-20-42-613_me.bmax.apatch.jpg](https://github.com/bmax121/KernelPatch/assets/154665575/4cc11a55-8e66-485c-86a7-e3265cadd121)

**Comment by tufeigunchu** [comment]
![Screenshot_2024-04-26-14-48-35-649_me bmax apatch](https://github.com/bmax121/KernelPatch/assets/88198403/51195d9e-07f4-453c-8d2e-aca1683231ef)
同型号表示很好使

**Comment by Alpha-Qian** [comment]
解决了？

**Comment by chengnan049** [comment]
> 解决了？

是的，大概三个月了，可以关了
