### ISSUE TITLE
Unable to start (OnePlus 9PRO) (5.4.61-qgki-ga139308) (ColorOS11.2/Android11)

### ISSUE THREAD

**Issue by suman666** [bmax121/KernelPatch#39]
**Currently, there is no immediate solution. You need to troubleshoot it yourself or provide the device to me for further investigation.**
https://pixeldrain.com/u/xCEeb3gM
[untitled.txt](https://github.com/bmax121/KernelPatch/files/13930733/untitled.txt)

**Comment by bmax121** [comment]
Currently, there is no immediate solution. You need to troubleshoot it yourself or provide the device to me for further investigation
