### ISSUE TITLE
meet this error, help wanted

### ISSUE THREAD

**Issue by nzcv** [bmax121/KernelPatch#4]
![image](https://github.com/bmax121/KernelPatch/assets/95273210/3c6c8198-5325-4003-a476-de8e57c4d89e)

**Comment by bmax121** [comment]
It could be known issue, please provide the boot.img

**Comment by nzcv** [comment]
https://github.com/yhnu/op7t/releases/download/v1.0/boot.img

**Comment by bmax121** [comment]
I tested it, and it works fine

**Comment by nzcv** [comment]
You test it on android?
