### ISSUE TITLE
include/linux/kernel.h 中的 sscanf 宏定义有误

### ISSUE THREAD

**Issue by cjybyjk** [bmax121/KernelPatch#44]
https://github.com/bmax121/KernelPatch/blob/f89cc0ebdbe2c480c95b8976ee997e33f8846a9a/kernel/linux/include/linux/kernel.h#L23

应为
```
#define sscanf(buf, fmt, ...) kfunc(sscanf)(buf, fmt, ##__VA_ARGS__)
```

**Comment by bmax121** [comment]
thank you
