### ISSUE TITLE
Patch Failed (Device Name) (Device Kerenl Version) 

### ISSUE THREAD

**Issue by bzmshang** [bmax121/KernelPatch#47]
**First, confirm whether your kernel has CONFIG_KALLSYMS_ALL=y enabled. If not or cannot be sure, please wait for support.**

The following two information are what I need to fix the problem

1. Your boot.img or kernel image

https://t.me/APatch_CN_Group/60093

Upload to here or file download path

2.  The real symbol informations corresponding to your boot.img or kernel
It can be obtained through the following two commands under **root**.
```shell
echo 1 > /proc/sys/kernel/kptr_restrict
cat /proc/kallsyms
```

Upload to here or file download path

[1.txt](https://github.com/bmax121/KernelPatch/files/14075999/1.txt)

- 手机是oneplus9p
- 内核版本是5.4.233-qgki-g31dce7dbd8de
- 修补boot的时候，我手机当前boot是【https://t.me/APatch_CN_Group/60045】版本，要修补的是【https://t.me/APatch_CN_Group/60093】版

- 截图
  1. 使用10446-26-gcbdda9a(10472)版本修补时候是
  ![原版](https://github.com/bmax121/KernelPatch/assets/111360926/de2411f5-9a56-446d-960b-ca73b1dce3c0)

  2. 使用【https://github.com/Admirepowered/APatch/actions/runs/7685449272】版本
  ![修改版](https://github.com/bmax121/KernelPatch/assets/111360926/a11b8ae8-d409-4faa-90a7-9bf099c814e4)

**Comment by bmax121** [comment]
[Uploading kernel.zip…]()
