### ISSUE TITLE
There is a risk of leakage of superkey.

### ISSUE THREAD

**Issue by sekaiacg** [bmax121/KernelPatch#59]
When reporting problems with various systems/third-party apps, users will be asked to upload log files.  If there is a superkey in the log, there is a risk of leakage.

example:
`[    6.388122] init: starting service 'exec 6 (/system/bin/truncate a12345678 /dev/kpatch a12345678 android_user post-fs-data-init -k)'...`

**Comment by bmax121** [comment]
I'll fix it,

**Comment by bmax121** [comment]
solved
