### ISSUE TITLE
A bin for patch the boot dron recovery

### ISSUE THREAD

**Issue by TDD788** [bmax121/KernelPatch#60]
Hello, I want you to provide a bin which has the utility of patching the boot from the recovery since I am a recovery builder and until now I can't get it together because I don't fully understand your tool

**Comment by bmax121** [comment]
But I don't know how to compat with recovery, Is there any simplest dome

**Comment by TDD788** [comment]
> But I don't know how to adapt with recovery, Is there any simplest dome

just creating the kpatch in well format to do some AKP style --superkey "BruhPosible"

**Comment by bmax121** [comment]
I can't understand, what's AKP style

**Comment by TDD788** [comment]
> I can't understand, what's AKP style

I mean an Android Kernel Patcher, practically APatch simplified in 1 bin

**Comment by TDD788** [comment]
Let it be something like you write the bin or command and it is executed in shell or bash style which does the APatch processes only with the kpatch and apd bins or those that are necessary It would be like a SU but to patch

**Comment by bmax121** [comment]
1: get boot image and unpack it to get kernel image
2: patch kernel image: kptools -p -k xxxxxx -s xxxxx

**Comment by TDD788** [comment]
Thanks now with that I will practically have a patcher

**Comment by TDD788** [comment]
I will use good termux and kptools
