### ISSUE TITLE
能单独把内核一些模块单独抽出来么？比如 inlinehook这种工具块。

### ISSUE THREAD

**Issue by w296488320** [bmax121/KernelPatch#62]
市面上很少用存c实现的inlinehook  ，还有各种内核相关的工具库。我最近也在搞这块，发现能用的很少。

**Comment by bmax121** [comment]
请细说

**Comment by w296488320** [comment]
比如inlinehook那部分，我现在自己也在做内核这块，但是hook用的kprobe做的hook 。
相当于你把内核那部分工具类，单独抽出来。

**Comment by bmax121** [comment]
kprobe 毫无疑更标准
