### ISSUE TITLE
Patch Failed (Oneplus 12) (6.1.57-android14-11-o-g793be1030a55) 

### ISSUE THREAD

**Issue by snipking** [bmax121/KernelPatch#68]
![2161710607788_ pic](https://github.com/bmax121/KernelPatch/assets/2351675/77b9f037-914a-429a-b7a5-3e719978d754)

1. Your kernel image. boot.img is too big, you can use 'magiskboot unpack boot.img' to get kernel image (which named 'kernel' after unpack)

[kernel.zip](https://github.com/bmax121/KernelPatch/files/14624603/kernel.zip)

**Comment by bmax121** [comment]
fixed
