### ISSUE TITLE
how to build kpimg?

### ISSUE THREAD

**Issue by tufeigunchu** [bmax121/KernelPatch#82]
I download offical kpimg from https://github.com/bmax121/KernelPatch/releases/download/0.10.5/kpimg-android
Also I clone this project and add my change. I got a build at https://github.com/tufeigunchu/KernelPatch/actions/runs/8834881997/artifacts/1447624671
```
pqy@3500X ~/src/APatch-main $ file /home/pqy/下载/kpimg-android 
/home/pqy/下载/kpimg-android: data
pqy@3500X ~/src/APatch-main $ file /home/pqy/tmp/kpimg.elf-android 
/home/pqy/tmp/kpimg.elf-android: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, with debug_info, not stripped
pqy@3500X ~/src/APatch-main $ ls -lh /home/pqy/下载/kpimg-android /home/pqy/tmp/kpimg.elf-android
-rw-r--r-- 1 pqy pqy 160K  4月25日 23:05 /home/pqy/下载/kpimg-android
-rw-r--r-- 1 pqy pqy 719K  4月25日 14:59 /home/pqy/tmp/kpimg.elf-android
```
I don't think they are the same format. So how to generate kpimg in fact?

**Comment by bmax121** [comment]
https://github.com/bmax121/KernelPatch/blob/main/doc/en/build.md
