### ISSUE TITLE
Device doesn't boot after patching with latest KernelPatch Version

### ISSUE THREAD

**Issue by Adarsh219** [bmax121/KernelPatch#86]
It was working fine with 0.10.5

but as soon as you switched to 0.10.6-dev in [064f079](https://github.com/bmax121/APatch/commit/064f079eccfa852f17ca22fdfac8921635ea296d). It stopped working

and 0.10.6-dev seems to have this single commit only - [8c2d2ae](https://github.com/bmax121/KernelPatch/commit/8c2d2ae91fdff4c0fc366d141e0a2f12f2248fa8)

So the real problem started with [8c2d2ae](https://github.com/bmax121/KernelPatch/commit/8c2d2ae91fdff4c0fc366d141e0a2f12f2248fa8)

Kindly look in to it ASAP.

**Comment by bmax121** [comment]
which brand and kernel version

**Comment by bmax121** [comment]
and upload your boot.img if you are convient, I will patch it and send it back to you for testing.
