### ISSUE TITLE
Patch failed

### ISSUE THREAD

**Issue by Memory2314** [bmax121/KernelPatch#9]
[boot.img](https://wwao.lanzouv.com/i7rfL1jgn5id)
[source code](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/chopin-r-oss)
Error message
![Screenshot_2023-12-31-12-40-53-267_me.bmax.apatch.jpg](https://github.com/bmax121/KernelPatch/assets/134070804/7aec761d-7f13-4877-8665-803749239e5d)

**Comment by bmax121** [comment]
I need the corresponding real symbol information to fix this problem. Can you help me take a look? It can be obtained through the following two commands under root.

echo 1 > /proc/sys/kernel/kptr_restrict
cat /proc/kallsyms

**Comment by Memory2314** [comment]
Please forgive me for being a rookie.
[kallsyms.txt](https://wwao.lanzouo.com/iVqy31knsm0f)

**Comment by Memory2314** [comment]
Please give me a reply.
