### ISSUE TITLE
help wanted, the magic number 0x7f  mean?

### ISSUE THREAD

**Issue by nzcv** [bmax121/KernelPatch#90]
https://github.com/bmax121/KernelPatch/blob/91df9a771b3dad1ef44b4f8401cb461ee7899ac3/tools/kallsym.c#L568C13-L568C16

in https://elixir.bootlin.com/linux/v5.19.17/source/include/linux/kallsyms.h

#define KSYM_NAME_LEN 128

**Comment by bmax121** [comment]
https://elixir.bootlin.com/linux/v6.1.90/source/include/linux/kallsyms.h

[#define [KSYM_NAME_LEN](https://elixir.bootlin.com/linux/v6.1.90/C/ident/KSYM_NAME_LEN) 512](https://patchwork.kernel.org/project/linux-kbuild/patch/20211206140313.5653-3-ojeda@kernel.org/)
